### ISSUE TITLE
Unhandled python exception in read callback: TypeError

### ISSUE THREAD

**Issue by is4it-lab** [evoila/collectsphere#21]
Hi,

we have strange Error messages from collectd:

Unhandled python exception in read callback: TypeError: Dataset VirtualMachine.virtualDisk.average.totalWriteLatency.millisecond not found.

adding the entry in vmware-types.db worked fine for some missing objekts but this on will be ignored.

grep VirtualMachine.virtualDisk.average.totalWriteLatency.millisecond /etc/collectd/vmware-types.db
VirtualMachine.virtualDisk.average.totalWriteLatency.millisecond        value:ABSOLUTE:0:U

maybe pathlength too long ?

best regards
robert

**Comment by dennis1987** [comment]
Hi robert,

it seems I have a typo in the configuration file. I fixed it with commit [63829d8](https://github.com/evoila/collectsphere/commit/63829d8d3c5772a6c3a092d17c8d7afbebb27571)

Best regards
Dennis

**Comment by dennis1987** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#21](https://trello.com/c/eZ0zE17O/3-21)

**Comment by robotsnowfall** [comment]
I'm still getting this error with v1.1.1

```
Unhandled python exception in read callback: TypeError: Dataset VirtualMachine.virtualDisk.average.totalWriteLatency.millisecond not found
```
Is there a way to selectively turn off collecting this metric? `VM_Counters` doesn't seem to have an effect.

If it helps, I am using the `write_graphite` plugin as well.
